markdown: rdiscount
pygments: true
permalink: /posts/:title
future: true
auto: false
rdiscount:
  extensions: [smart]
url: http://thehackerwithin.github.com/wisconsin
name: Hacker Within, Wisconsin
description: An initial blog and site for THW at UW-Madison
twitter: hackerwithin
gravatar_url: http://www.gravatar.com/avatar/0203c034a145af6cc2576d56cdb4cf73
disqus_username: hackerwithinadmin

